version: '2.4'

services:
  mailer:
    container_name: mailer
    image: mailer
    build:
      context: ./docker/mailer
      args:
        domain: rucreditor.ru
        user: user
        password: password
    ports:
      - 25:25
      - 110:110
      - 143:143
    networks:
      - mailer-network
    command: /entrypoint.sh

networks:
  mailer-network:
    external: true
