version: '2.2'

services:
  mailer:
    container_name: mailer
    image: mailer
    build:
      context: ./docker/mailer
      args:
        domain: rucreditor.ru
        user: user
        password: password
    environment:
      HOST_HOSTNAME: rucreditor.ru
    volumes:
      - ./var/dkim/keys:/etc/opendkim/keys
    ports:
      - 110:110
      - 143:143
      - 125:25
    networks:
      - mailer-network
    command: /entrypoint.sh

networks:
  mailer-network:
    external: true
