version: '2.2'

services:
  mail-server:
    container_name: mail-server
    image: mailer/mail-server
    env_file:
      - ./env/.env
    build:
      context: ./docker/mailer
    volumes:
      - ./var/dkim/keys:/etc/opendkim/keys
    ports:
      - "25:25"
      - 110:110
      - 143:143
    restart: always
    networks:
      - mailer-network
    command: /entrypoint.sh

networks:
  mailer-network:
    external: true
